### ISSUE TITLE
wss://

### ISSUE THREAD

**Issue by NewSoupVi** [black-sliver/apclientpp#9]
Berserker is dropping ws:// for archipelago.gg, it seems.

So this comment is now coming to haunt us:

// fix up URI (add ws:// and default port if none is given)
// TODO: move this to the front-end once we have wss:// and ws://

Correct behavior according to Berserker would be this: "if a connection returns malformed data, and protocol was ws, we set it to wss and retry"

:)

**Comment by NewSoupVi** [comment]
It gets worse: For me, trying to connect to wss://archipelago.gg:##### just straight up *crashes* on some sort of memory read exception. o_o

**Comment by NewSoupVi** [comment]
In wsswrap:

![image](https://user-images.githubusercontent.com/57900059/214484614-d9febf84-2291-4d95-ba95-c3b261ed8331.png)

In apclient.hpp:

![image](https://user-images.githubusercontent.com/57900059/214484687-4e2b65e5-4918-4041-a924-b4fcbdc6d3e6.png)

Both are up to date.

**Comment by black-sliver** [comment]
Implemented in 034589499fcac743eb9af7bb2fc5d3d879321153
